# euler_project_2.rb
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
el1 = 0
el2 = 1

sum = 0

while el2 < 4000000
	puts el2
	el1, el2 = el2, el1 + el2
	sum += el2 if el2 % 2 == 0 
end
puts sum
